#!/usr/bin/env groovy

node {
	checkout scm
	def image

	// only process the master branch for now
	// TODO: i think this can be configured in the job config
	if (env.BRANCH_NAME == 'master') {

		stage('Clone repository') {
			checkout scm
		}

		stage('Build') {
			environment {
			    DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
			}
			image = docker.build("{{ cookiecutter.docker_hub_username }}/{{ cookiecutter.project_name }}:${env.BUILD_ID}")
		}

		stage('Test') {
		}

		stage('Push') {
			// only deploy successful builds
			if (currentBuild.result == null || currentBuild.result == 'SUCCESS') {
				docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
					image.push("${env.BUILD_ID}")
					image.push("latest")
				}
			}
		}
	}
}
