- job:
    name: '{{ cookiecutter.project_name }}'
    project-type: multibranch
    script-path: 'jenkins/Jenkinsfile'
    scm:
        - github:
            repo-owner: '{{ cookiecutter.github_user }}'
            repo: '{{ cookiecutter.project_name }}'
            credentials-id: 'github-repo-scan'
